version: '3.8'

services:
  database:
    image: mysql:8.0
    container_name: bank_app_mysql_db
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: Password123!
      MYSQL_DATABASE: bank
      MYSQL_USER: bank_app
      MYSQL_PASSWORD: BankApp123!